
WITH table_totals (polling_place_id, total_tables) AS (
VALUES
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 01' AND pp.name = '01 - COL SAN JOSE SEDE MERCEDES ABREGO'), 35),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 01' AND pp.name = '02 - COL SAGRADO SEDE ANTONIA SANTO'), 33),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 01' AND pp.name = '03 - COL SAGRADO CORAZON DE JESUS'), 52),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 01' AND pp.name = '04 - COLEGIO ANTONIO NARIÑO'), 22),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 01' AND pp.name = '05 - IE COL SAN JOSE DE CUCUTA'), 15),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 02' AND pp.name = '01 - SALESIANO'), 42),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 02' AND pp.name = '02 - MERCEDES ABREGO SEDE JARDIN NACIONAL'), 40),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 02' AND pp.name = '03 - UNIVERSIDAD FRANCISCO DE PAULA SANTANDER'), 44),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 02' AND pp.name = '04 - COLEGIO LA SALLE'), 48),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 02' AND pp.name = '05 - GIMNASIO SANTO DOMINGO'), 31),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 03' AND pp.name = '01 - COL PABLO CORREA SEDE CLUB DE LEONES'), 39),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 03' AND pp.name = '02 - COL FRANCISCO JOSE CALDAS'), 46),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 03' AND pp.name = '03 - CLUB DE LEONES SEDE I.E. BOCONO'), 21),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 03' AND pp.name = '04 - IE MISAEL PASTRANA BORRERO'), 38),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 03' AND pp.name = '05 - FCO JOSE DE CALDAS SEDE SAN PEDRO CLAVER'), 17),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 03' AND pp.name = '06 - IE PABLO CORREA LEON'), 4),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '01 - ESC. MARCO FIDEL SUAREZ'), 18),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '02 - IE PABLO CORREA SEDE MARIA AUXILIADORA'), 29),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '03 - COLEGIO SIMON BOLIVAR'), 33),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '04 - COLEGIO PADRE LUIS VARIARA'), 38),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '05 - COL BAS CLUB DE LEONES No 29'), 15),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '06 - I.E. MON. JAIME PRIETO AMAYA'), 9),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '07 - COL. CARLOS PEREZ ESCALANTE'), 24),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '08 - CENTRO INT. CIUDADANA PRADOS DEL ESTE'), 26),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 04' AND pp.name = '09 - IE SAN JUAN BOSCO - CLUB DE LEONES'), 4),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '01 - COL . GREMIOS UNIDOS SEDE SIMON BOLIVAR'), 36),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '02 - GUAIMARAL S. HERMOGENES MAZA'), 40),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '03 - INEM'), 42),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '04 - COL ANDRES BELLO'), 32),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '05 - COL ORIENTAL No 26'), 35),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '06 - INEM SEDE MIGUEL MULLER'), 18),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '07 - COL BASICO GUAIMARAL No 25'), 17),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '08 - CENTRO INTEGRACIÓN CIUDADANA EL BOSQUE'), 9),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '09 - INSTITUTO TECNICO MERCEDES ABREGO'), 7),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 05' AND pp.name = '10 - COL. MPAL MARIA CONCEPCION LOPERENA'), 15),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '01 - COL ANDRES BELLO SEDE LAURA VI'), 13),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '02 - COL MUNICIPAL AEROPUERTO'), 46),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '03 - COL EUSTORGIO COLMENARES BAUTI'), 29),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '04 - ESCUELA EL CERRITO'), 4),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '05 - INST EDUCATIVA SAN JOSE'), 30),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '06 - COL TOLEDO PLATA'), 33),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '07 - COL MPAL SEDE MARIA OFELIA VILLAMIZAR'), 12),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '08 - CENTRO INTEGRACION CIUDADANA METROPOLI'), 8),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '09 - IE ANCIZAR OCAMPO - COL ANDRES BELLO'), 4),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 06' AND pp.name = '10 - IE VIRGILIO BARCO - COL MPAL AEROPUERTO'), 3),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '01 - ESC. URBANA JOSE CELESTINO MUTIS No 31'), 32),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '02 - COL SAN BARTOLOME'), 32),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '03 - COL INTEGRADO JUAN ATALAYA'), 40),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '04 - COL MARIANO OSPINA RODRIGUEZ'), 43),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '05 - COL BUENOS AIRES'), 23),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '06 - COL BASICO CAMILO DAZA'), 17),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '07 - COL CONCEJO DE CUCUTA'), 17),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '08 - ESC. COMUNEROS # 33 - COL SAN BARTOLOME'), 13),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '09 - COL .SANTOS APOSTOLES SD EL ROSAL'), 7),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 07' AND pp.name = '10 - IE MARIANO OSPINA R SD MONS. LUIS PEREZ'), 9),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '01 - ESC No 38 TEODORO GUTIERREZ'), 30),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '02 - I.E. PADRE MANUEL BRICEÑO JAUREGUI'), 47),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '03 - COL RAFAEL URIBE URIBE'), 41),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '04 - INST TECN CARLOS RAMIREZ PARIS'), 47),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '05 - COL HERMANO RODULFO ELOY'), 31),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '06 - CARLOS RAMIREZ SEDE NTRA SRA DE MONGUI'), 25),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '07 - I.E. EL RODEO'), 17),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '08 - I.E. PEDRO CUADRO HERRERA'), 4),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 08' AND pp.name = '09 - IE RAFAEL URIBE SD CARLOS RAMIREZ'), 7),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '01 - COL NTRA SRA DE BELEN 23 VARON'), 43),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '02 - COL JULIO PEREZ FERRERO'), 36),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '03 - IE MANUEL FERNANDEZ DE NOVOA'), 29),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '04 - COL NTRA SRA DE BELEN LA DIVINA PASTORA'), 21),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '05 - COL GARCIA HERREROS SEDE ESC 28 DE FEBRERO'), 24),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '06 - COL . BASICO LOS ALPES'), 10),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 09' AND pp.name = '07 - ESC. URB. VARONES No 28 ATANASIO GIR.'), 5),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 10' AND pp.name = '01 - SANTO ANGEL SEDE JOSE EUSEBIO'), 22),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 10' AND pp.name = '02 - COL LUIS CARLOS GALAN SARMIENTO'), 38),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 10' AND pp.name = '03 - ESC FRANCISCO DE PAULA ANDRADE No 9'), 29),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 10' AND pp.name = '04 - ALEJANDRO GUTIERREZ SEDE SAN JUAN BOSCO'), 14),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 10' AND pp.name = '05 - IE NUESTRA SEÑORA DEL ROSARIO'), 22),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 90' AND pp.name = '01 - NORMAL MARIA AUXILIADORA'), 18),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 98' AND pp.name = '01 - CARCEL'), 1),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 98' AND pp.name = '02 - CARCEL DE MUJERES'), 1),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '01 - PUERTO VILLAMIZAR'), 1),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '03 - BANCO DE ARENA'), 2),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '04 - PALMARITO'), 2),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '05 - LA BUENA ESPERANZA'), 12),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '17 - LIMONCITO'), 2),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '20 - AGUACLARA'), 11),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '25 - GUAMARITO'), 3),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '27 - RICAURTE'), 2),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '37 - SAN FAUSTINO'), 4),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '45 - EL CARMEN DE TONCHALA'), 2),
((SELECT pp.polling_place_id FROM vota_mas.polling_places pp JOIN vota_mas.voting_zones vz ON vz.voting_zone_id = pp.voting_zone_id WHERE vz.name = 'ZONA 99' AND pp.name = '53 - SAN PEDRO'), 3)
)
INSERT INTO vota_mas.voting_tables (polling_place_id, table_number)
SELECT totals.polling_place_id, table_number
FROM table_totals totals
CROSS JOIN LATERAL generate_series(1, totals.total_tables) AS table_number
ON CONFLICT (polling_place_id, table_number) DO NOTHING;
